config/routes.rb
Rails.application.routes.draw do

  resources :users, :sessions, :game, :questions

  get '/signup'  => 'users#new'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get '/start' => 'game#game'

  root 'sessions#index'

end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_one :game
end

app/models/user.rb
class User < ActiveRecord::Base

  validates :mail, presence: true,
            uniqueness: true, length: { minimum: 3 }
  validates :password, presence: true,
            confirmation: true,
            length: { in: 6..20 }, allow_nil: true

  has_secure_password

  has_one :game

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  def require_user
    redirect_to '/' unless current_user
  end
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  def index
    @question = Question.find(1)
    @game = Game.new(user_id: current_user.id, question_id: @question.id)
    @game.save
  end

  def new

  end

  def create
  end

  def game
    @game = Game.find_by_user_id(current_user.id)
    if @game != nil
      if @game.count_question < 25
      @question = Question.find(random)
      @game.update_attributes(count_question: @game.count_question + 1, question_id: @question.id, current_score: isGood)


      respond_to do |format|
        format.js { render :layout=>false }
        format.html { render 'game/index' }
      end

      else
      @game = Game.find_by_user_id(current_user.id)

      respond_to do |format|
        format.js { render 'game/gameover' }
        format.html { redirect_to '/' }
        @game.destroy
      end
      end
    else

      @question = Question.find(random)
      @game = Game.new(user_id: current_user.id, question_id: @question.id)
      @game.save
      render 'game/index'

    end

  end


  def isGood
    answer = Question.find(@game.question_id)
    if params[:answer] == answer.good
      @game.current_score + 100
    else
      @game.current_score
    end

  end

  def random
    rnd = Random.new
    rnd.rand(1..5)
  end


end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def new
  end
  def create
    @question = Question.new(question_params)
    if @question.save
      redirect_to '/questions/new'
    else
      redirect_to '/signup'
    end
  end

  private
  def question_params
    params.require(:question).permit(:title, :A, :B, :C, :D, :good)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index

  end

  def new
  end

  def create
    @user = User.find_by_mail(params[:session][:mail])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to '/'
    else
      flash[:danger] = "Неправильна пошта або пароль"
      redirect_to '/'
    end
  end
  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user, only: [:edit, :update, :destroy]
  def index
    @users = User.all
  end

  def show
  end

  def new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end


  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      flash[:success] = "Профіль успішно оновлено"
      redirect_to '/'
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find_by_id(params[:id])
    @user.destroy
    if @user.destroy
      session[:user_id] = nil
      redirect_to '/'
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :mail, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/game/_gameover.html.erb
<div class="question">
  <div class="title">
    Гру закінчено з результатом у <%= @game.current_score %> балів
  </div>
  <div class="options">
      <%= link_to 'Повторити', start_path, method: 'get', class: 'option' %>
      <%= link_to 'На головну', root_path, method: 'get', class: 'option' %>
  </div>

</div>

app/views/game/_question.html.erb
<div class="question">
  <div class="title">
    <%= @question.title %>
  </div>
  <div class="options">
    <%= link_to @question.A, start_path(:answer => @question.A), method: 'get', remote: true, class: 'option' %>
    <%= link_to @question.B, start_path(:answer => @question.B), method: 'get', remote: true, class: 'option' %>
    <%= link_to @question.C, start_path(:answer => @question.C), method: 'get', remote: true, class: 'option' %>
    <%= link_to @question.D, start_path(:answer => @question.D), method: 'get', remote: true, class: 'option' %>
  </div>

</div>

app/views/game/game.js.erb
$(".questions").html("<%= escape_javascript(render 'question') %>");

app/views/game/gameover.js.erb
$(".questions").html("<%= escape_javascript(render 'gameover') %>");

app/views/game/index.html.erb
<div class="questions">
  <%= render 'game/question' %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">

      <div class='navbar-form navbar-right'>
        <% if current_user %>
<!--            <%= link_to 'Мої замовлення',  method: 'get', class: 'btn btn-success' %>
            <%= link_to 'Зробити замовлення',  method: 'get', class: 'btn btn-success' %>-->
            <i class="glyphicon glyphicon-user white"></i> <i style="color: white; margin-right: 10px" ><%= current_user.name %> </i> <a class="btn btn-success" data-toggle="dropdown" href="#"><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to edit_user_path(current_user) do %> <i class="glyphicon glyphicon-pencil"> </i> Редагувати профіль </li> <% end %>
              <li class="divider"></li>
              <li><%= link_to 'Вийти', logout_path, method: 'delete', class: 'btn btn-success' %></li>
            </ul>


        <% else %>

            <%= form_for(:session, url: login_path) do |f| %>

                <%= f.text_field :mail, placeholder: 'Eлектронна пошта', class: 'form-control' %>


                <%= f.password_field :password, placeholder: 'Пароль', class: 'form-control' %>


                <%=  f.submit value='Вхід', class: 'btn btn-success' %>
                <%= link_to 'Зареєструватись', signup_path, method: 'get', class: 'btn btn-success' %>
            <% end %>
        <% end %>
      </div>
    </div>
  </div><!--/.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Geotest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navbar' %>

<div class="flash">
  <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
</div>

<%= yield %>

</body>
</html>

app/views/questions/new.html.erb
<div class="container" id="container1">
  <div class="row centered-form">
    <div class="col-xs-12 col-sm-8 col-md-4 col-sm-offset-2 col-md-offset-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title text-center">Додати питання</h3>
        </div>
        <div class="panel-body">
          <%= form_for :question, url: questions_path, method: :post do |f| %>
              <div class="form-group">
                <%= f.text_field :title, class: 'form-control input-sm', placeholder: 'Введіть запитання...' %>
              </div>
              <div class="row">
                <div class="col-xs-6 col-sm-6 col-md-6">
                  <div class="form-group">
                    <%= f.text_field :A, class: 'form-control input-sm', placeholder: 'Варіант 1...' %>
                  </div>
                </div>
                <div class="col-xs-6 col-sm-6 col-md-6">
                  <div class="form-group">
                    <%= f.text_field :B, class: 'form-control input-sm', placeholder: 'Варіант 2...' %>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-xs-6 col-sm-6 col-md-6">
                  <div class="form-group">
                    <%= f.text_field :C, class: 'form-control input-sm', placeholder: 'Варіант 3...' %>
                  </div>
                </div>
                <div class="col-xs-6 col-sm-6 col-md-6">
                  <div class="form-group">
                    <%= f.text_field :D, class: 'form-control input-sm', placeholder: 'Варіант 4...' %>
                  </div>
                </div>
              </div>
              <div class="form-group">
                <%= f.text_field :good, class: 'form-control input-sm', placeholder: 'Введіть правильну...' %>
              </div>
              <%= f.submit value: 'Додати', class: 'btn btn-block btn-success' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<style>

  .centered-form {
    margin-top: 120px;
    margin-bottom: 120px;
  }

  .centered-form .panel {
    background: rgba(255, 255, 255, 0.8);
    box-shadow: rgba(0, 0, 0, 0.3) 20px 20px 20px;
  }
</style>

app/views/users/new.html.erb
<div class="container" id="container1">
  <div class="row centered-form">
    <div class="col-xs-12 col-sm-8 col-md-4 col-sm-offset-2 col-md-offset-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title text-center">Реєстрація</h3>
        </div>
        <div class="panel-body">
          <%= form_for :user, url: users_path, method: :post do |f| %>
              <div class="form-group">
                <%= f.text_field :name, class: 'form-control input-sm', placeholder: 'Введіть iм’я...' %>
              </div>
              <div class="form-group">
                <%= f.text_field :mail, class: 'form-control input-sm', placeholder: 'Введіть пошту...' %>
              </div>
              <div class="row">
                <div class="col-xs-6 col-sm-6 col-md-6">
                  <div class="form-group">
                    <%= f.password_field :password, class: 'form-control input-sm', placeholder: 'Введіть пароль...' %>
                  </div>
                </div>
                <div class="col-xs-6 col-sm-6 col-md-6">
                  <div class="form-group">
                    <%= f.password_field :password_confirmation, class: 'form-control input-sm', placeholder: 'Повторіть пароль...' %>
                  </div>
                </div>
              </div>
              <%= f.submit value: 'Зареєструватись', class: 'btn btn-block btn-success' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<style>

  .centered-form {
    margin-top: 120px;
    margin-bottom: 120px;
  }

  .centered-form .panel {
    background: rgba(255, 255, 255, 0.8);
    box-shadow: rgba(0, 0, 0, 0.3) 20px 20px 20px;
  }
</style>